server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123457
    url: jdbc:mysql://101.126.20.67:3306/test?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  freemarker:
  mvc:
    settings:
      classic_compatible: true #处理空值
      datetime_format: yyy-MM-dd HH:mm
      number_format: 0.##
  mail:
    host: smtp.qq.com
    port: 587
    username: 772105823@qq.com
    password: iwaiklxicmkkbbgf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
    from: 772105823@qq.com
  redis:
    host: 101.126.20.67
    port: 6379
    password: zhangxin  # 如果有密码，填写密码；没有密码则留空
    jedis:
      pool:
        max-idle: 10          # 最大空闲连接数
        min-idle: 1           # 最小空闲连接数
        max-active: 100       # 最大活跃连接数
        max-wait: 5000        # 获取连接的最大等待时间（毫秒）
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.melo.gold.entity
  mapper-locations: mapper/*.xml


