server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://172.16.23.99:3306/whitelist?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
    username: shkuser
    password: shkpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
  mvc:
    settings:
      classic_compatible: true #处理空值
      datetime_format: yyy-MM-dd HH:mm
      number_format: 0.##
  mail:
    host: smtp.qq.com
    port: 587
    username: 772105823@qq.com
    password: iwaiklxicmkkbbgf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
    from: 772105823@qq.com
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.melo.gold.entity
  mapper-locations: mapper/*.xml
